services:
  django:
    build: .
    command: python backend/core/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env

  meme_service:
    build: .
    command: python -m backend.services.meme_service.app
    ports:
      - "5001:5000"
    env_file:
      - .env